config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'
  post    'login',      to: 'sessions#create'
  delete  'logout',     to: 'sessions#destroy'
  get     'dashboard',  to: 'pages#index'
  get     ':id',       to: 'pages#details', as: 'details'
  post    'register',   to: 'apis#createRegistration'

end

app/models/artist.rb
class Artist < Parse::Object
  # See: https://github.com/modernistik/parse-stack#defining-properties

  # You can change the inferred Parse table/collection name below
  # parse_class "Artist"

  property :name, :string

  # See: https://github.com/modernistik/parse-stack#cloud-code-webhooks
  # define a before save webhook for Artist
  webhook :before_save do
    artist = parse_object
    # perform any validations with artist
    # use `error!(msg)` to fail the save
    # ...
    artist
  end

  ## define an after save webhook for Artist
  #
  # webhook :after_save do
  #   artist = parse_object
  #
  # end

  ## define a before delete webhook for Artist
  # webhook :before_delete do
  #   artist = parse_object
  #   # use `error!(msg)` to fail the delete
  #   true # allow the deletion
  # end

  ## define an after delete webhook for Artist
  # webhook :after_delete do
  #   artist = parse_object
  # end

  ## Example of a CloudCode Webhook function
  ## define a `helloWorld` Parse CloudCode function
  # webhook :function, :helloWorld do
  #   "Hello!"
  # end

end

app/models/installation.rb
class Parse::Installation < Parse::Object
  # See: https://github.com/modernistik/parse-stack#parseinstallation
  # add additional properties here
end

app/models/registration.rb
class Registration < Parse::Object
  # See: https://github.com/modernistik/parse-stack#defining-properties


  # form data fields
  property :fullName, :string
  property :email, :string
  property :phone, :string
  property :address, :string
  property :region, :string
  property :type, :string
  property :nation, :string
  property :hasVisa, :boolean
  property :budget, enum: [:bigBudget, :moderateBudget, :smallBudget]
  property :time, enum: [:goThisMonth, :goNextMonth, :goOtherTime]
  property :request, :string

  # referrer data
  property :original_url, :string
  property :utm_source, :string
  property :utm_medium, :string
  property :utm_campaign, :string
  property :gclid, :string

  # client devices
  property :device, :string
  property :system, :string

  # user behavior
  property :readingTime, :float
  property :scrolled, :float

  # potential score
  property :potentialScore, :float, default: lambda { |x|
    score = 0
    # maximum score is 10, will be calculated base on hasVisa, budget, time, readingTime, scrolled
    score += 2 if x.hasVisa?

    score += 2 if x.bigBudget?
    score += 1 if x.moderateBudget?

    score += 2 if x.goThisMonth?
    score += 1 if x.goNextMonth?

    score += 2 if (10.0 <= x.readingTime)
    score += 1 if x.readingTime.between?(5, 10)

    score += (x.scrolled * 2 / 100)

    return score
  }

  # See: https://github.com/modernistik/parse-stack#cloud-code-webhooks
  # define a before save webhook for Registration
  webhook :before_save do
    registration = parse_object
    # perform any validations with artist
    # use `error!(msg)` to fail the save
    # ...
    registration
  end

  ## define an after save webhook for Artist
  #
  # webhook :after_save do
  #   artist = parse_object
  #
  # end

  ## define a before delete webhook for Artist
  # webhook :before_delete do
  #   artist = parse_object
  #   # use `error!(msg)` to fail the delete
  #   true # allow the deletion
  # end

  ## define an after delete webhook for Artist
  # webhook :after_delete do
  #   artist = parse_object
  # end

  ## Example of a CloudCode Webhook function
  ## define a `helloWorld` Parse CloudCode function
  # webhook :function, :helloWorld do
  #   "Hello!"
  # end

end

app/models/role.rb
class Parse::Role < Parse::Object
  # See: https://github.com/modernistik/parse-stack#parserole
  # add additional properties here
end

app/models/session.rb
class Parse::Session < Parse::Object
  # See: https://github.com/modernistik/parse-stack#parsesession
  # add additional properties here
end

app/models/user.rb
class Parse::User < Parse::Object
  # add additional properties

  # define a before save webhook for Parse::User
  # webhook :before_save do
  #   obj = parse_object # Parse::User
  #   # make changes to record....
  #   obj # will send the proper changelist back to Parse-Server
  # end

end

app/models/webhooks.rb
# See: https://github.com/modernistik/parse-stack#cloud-code-webhooks
Parse::Webhooks.route(:function, :helloWorld) do
  #  use the Parse::Payload instance methods in this block
  name = params['name'].to_s #function params

  # will return proper error response
  # error!("Missing argument 'name'.") unless name.present?

  name.present? ? "Hello #{name}!" : "Hello World!"
end

app/controllers/apis_controller.rb
class ApisController < ApplicationController
  protect_from_forgery prepend: true

  def createRegistration
    Parse.use_shortnames!
    parse_params = {
      fullName: params[:fullName],
      email: params[:email],
      phone: params[:phone],
      address: params[:address],
      region: params[:region],
      type: params[:type],
      nation: params[:nation],
      hasVisa: params[:hasVisa] == 'true' ? true : false,
      budget: params[:budget].parameterize.underscore.to_sym,
      time: params[:time].parameterize.underscore.to_sym,
      request: params[:request],
      original_url: params[:original_url],
      utm_source: params[:utm_source],
      utm_medium: params[:utm_medium],
      utm_campaign: params[:utm_campaign],
      gclid: params[:gclid],
      device: params[:device],
      system: params[:system],
      readingTime: params[:readingTime].to_f,
      scrolled: params[:scrolled].to_f
    }
    registration = Registration.new(parse_params)
    registration.save
  end

  private

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= Parse::User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def login
  end

  def index
    Parse::use_shortnames!
    if !logged_in?
      flash[:error] = "You are not authorized to view dashboard"
      redirect_to root_path
    end

    @registrations = Registration.all
  end

  def details
    Parse::use_shortnames!
    @registration = Registration.find(params[:id])
    render 'details'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if !logged_in?
      render 'login'
    else
      redirect_to dashboard_path
    end
  end

  def create
    user = Parse::User.login(params[:session][:username], params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid login data"
      render 'login'
    else
      session[:user_id] = user.id
      session[:session_token] = user.session_token
      flash[:success] = "You have successfully logged in."
      redirect_to dashboard_path
    end
  end

  def destroy
    if !logged_in?
      flash.now[:error] = "You did not logged in"
    else
      current_user.logout
      session[:user_id] = nil
      session[:session_token] = nil
      flash.now[:success] = "You have successfully logged out."
    end
    render 'login'
  end

  private
	def session_params
		params.require(:session).permit(:username, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
<script type="text/javascript">
  $("body").removeAttr('class').addClass("top-center-fullwidth");
  $.toast({
        text: '<%= msg %>',
        position: 'top-center',
        loaderBg:'#3cb878',
        icon: '<%= name %>',
        hideAfter: 3500,
        stack: 6
      });
</script>
<% end %>

app/views/layouts/_topnav.html.erb
<!-- Top Menu Items -->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <a id="toggle_nav_btn" class="toggle-left-nav-btn inline-block mr-20 pull-left" href="javascript:void(0);"><i class="fa fa-bars"></i></a>
  <%= link_to image_tag("logo-kilala.png", alt: "Kilala Tour Japan", class: "brand-img pull-left"), dashboard_path %>
  <ul class="nav navbar-right top-nav pull-right">
    <li>
      <a href="javascript:void(0);" data-toggle="collapse" data-target="#site_navbar_search">
      <i class="fa fa-search top-nav-icon"></i>
      </a>
    </li>
    <li>
      <a id="open_right_sidebar" href="javascript:void(0);"><i class="fa fa-cog top-nav-icon"></i></a>
    </li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-th top-nav-icon"></i></a>
      <ul class="dropdown-menu app-dropdown" data-dropdown-in="fadeIn" data-dropdown-out="fadeOut">
        <li>
          <ul class="app-icon-wrap">
            <li>
              <a href="#" class="connection-item">
              <i class="pe-7s-umbrella txt-info"></i>
              <span class="block">weather</span>
              </a>
            </li>
            <li>
              <a href="#" class="connection-item">
              <i class="pe-7s-mail-open-file txt-success"></i>
              <span class="block">e-mail</span>
              </a>
            </li>
            <li>
              <a href="#" class="connection-item">
              <i class="pe-7s-date txt-primary"></i>
              <span class="block">calendar</span>
              </a>
            </li>
            <li>
              <a href="#" class="connection-item">
              <i class="pe-7s-map txt-danger"></i>
              <span class="block">map</span>
              </a>
            </li>
            <li>
              <a href="#" class="connection-item">
              <i class="pe-7s-comment txt-warning"></i>
              <span class="block">chat</span>
              </a>
            </li>
            <li>
              <a href="#" class="connection-item">
              <i class="pe-7s-notebook"></i>
              <span class="block">contact</span>
              </a>
            </li>
          </ul>
        </li>
        <li class="divider"></li>
        <li class="text-center"><a href="#">More</a></li>
      </ul>
    </li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell top-nav-icon"></i><span class="top-nav-icon-badge">5</span></a>
      <ul  class="dropdown-menu alert-dropdown" data-dropdown-in="fadeIn" data-dropdown-out="fadeOut">
        <li>
          <div class="streamline message-box message-nicescroll-bar">
            <div class="sl-item">
              <div class="sl-avatar avatar avatar-sm avatar-circle">
                <%= image_tag("user.png", alt: "Avatar", class: "img-responsive img-circle") %>
              </div>
              <div class="sl-content">
                <a href="javascript:void(0)" class="inline-block capitalize-font  pull-left">Sandy Doe</a>
                <span class="inline-block font-12  pull-right">12/10/16</span>
                <div class="clearfix"></div>
                <p>Neque porro quisquam est!</p>
              </div>
            </div>
            <hr/>
            <div class="sl-item">
              <div class="icon">
                <i class="fa fa-spotify"></i>
              </div>
              <div class="sl-content">
                <a href="javascript:void(0)" class="inline-block capitalize-font  pull-left">
                2 voice mails</a>
                <span class="inline-block font-12  pull-right">2pm</span>
                <div class="clearfix"></div>
                <p>Neque porro quisquam est</p>
              </div>
            </div>
            <hr/>
            <div class="sl-item">
              <div class="icon">
                <i class="fa fa-whatsapp"></i>
              </div>
              <div class="sl-content">
                <a href="javascript:void(0)" class="inline-block capitalize-font  pull-left">8 voice messanger</a>
                <span class="inline-block font-12 pull-right">1pm</span>
                <div class="clearfix"></div>
                <p>8 texts</p>
              </div>
            </div>
            <hr/>
            <div class="sl-item">
              <div class="icon">
                <i class="fa fa-envelope"></i>
              </div>
              <div class="sl-content">
                <a href="javascript:void(0)" class="inline-block capitalize-font  pull-left">2 new messages</a>
                <span class="inline-block font-12  pull-right">1pm</span>
                <div class="clearfix"></div>
                <p>ashjs@gmail.com</p>
              </div>
            </div>
            <hr/>
            <div class="sl-item">
              <div class="sl-avatar avatar avatar-sm avatar-circle">
                <img class="img-responsive img-circle" src="dist/img/user4.png" alt="avatar"/>
              </div>
              <div class="sl-content">
                <a href="javascript:void(0)" class="inline-block capitalize-font  pull-left">Sandy Doe</a>
                <span class="inline-block font-12  pull-right">1pm</span>
                <div class="clearfix"></div>
                <p>Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit</p>
              </div>
            </div>
          </div>
        </li>
      </ul>
    </li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle pr-0" data-toggle="dropdown"><%= image_tag("user1.png", alt: "user_auth", class: "user-auth-img img-circle") %><span class="user-online-status"></span></a>
      <ul class="dropdown-menu user-auth-dropdown" data-dropdown-in="fadeIn" data-dropdown-out="fadeOut">
        <li>
          <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
        </li>
        <li>
          <a href="#"><i class="fa fa-fw fa-credit-card-alt"></i> my balance</a>
        </li>
        <li>
          <a href="#"><i class="fa fa-fw fa-envelope"></i> Inbox</a>
        </li>
        <li>
          <a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>
        </li>
        <li class="divider"></li>
        <li>
          <%= link_to 'Log Out', logout_path, method: :delete %>
        </li>
      </ul>
    </li>
  </ul>
  <div class="collapse navbar-search-overlap" id="site_navbar_search">
    <form role="search">
      <div class="form-group mb-0">
        <div class="input-search">
          <div class="input-group">
            <input type="text" id="overlay_search" name="overlay-search" class="form-control pl-30" placeholder="Search">
            <span class="input-group-addon pr-30">
            <a  href="javascript:void(0)" class="close-input-overlay" data-target="#site_navbar_search" data-toggle="collapse" aria-label="Close" aria-expanded="true"><i class="fa fa-times"></i></a>
            </span>
          </div>
        </div>
      </div>
    </form>
  </div>
</nav>
<!-- /Top Menu Items -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
		<title>HIS Administrator Area</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<!-- Favicon -->
		<link rel="shortcut icon" href="favicon.ico">
		<link rel="icon" href="favicon.ico" type="image/x-icon">

    <!-- Custom CSS -->
    <% if content_for?(:head) %>
      <%= yield(:head) %>
    <% end %>

	</head>
	<body>
		<div class="wrapper pa-0">
			<!-- Main Content -->
			<%= yield %>
			<!-- /Main Content -->
		</div>
		<%= render 'layouts/messages' %>
		<!-- /#wrapper -->

		<!-- JavaScript -->

		<!-- jQuery -->
		<script src="vendors/bower_components/jquery/dist/jquery.min.js"></script>

		<!-- Bootstrap Core JavaScript -->
		<script src="vendors/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
		<script src="/vendors/bower_components/jasny-bootstrap/dist/js/jasny-bootstrap.min.js"></script>
		<script src="/dist/js/jquery.slimscroll.js"></script>
		<script src="/dist/js/dropdown-bootstrap-extended.js"></script>
		<script src="/dist/js/init.js"></script>
		<% if content_for?(:bottom) %>
      <%= yield(:bottom) %>
    <% end %>
	</body>
</html>

app/views/pages/details.html.erb
<div class="wrapper">
	<%= render 'layouts/topnav' %>
  <%= render 'layouts/sidebar-left' %>
  <%= render 'layouts/sidebar-right' %>

    <!-- Main Content -->
    <div class="page-wrapper">
        <div class="container-fluid">

    		<!-- Title -->
    		<div class="row heading-bg  bg-red">
    			<div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
    				<h5 class="txt-light">Registration Details</h5>
    			</div>
    			<!-- Breadcrumb -->
    			<div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
    				<ol class="breadcrumb">
    					<li><a href="#">ID: <%= @registration.id %></a></li>
    				</ol>
    			</div>
    			<!-- /Breadcrumb -->
    		</div>


    	</div>
    	<!-- Footer -->
    	<footer class="footer container-fluid pl-30 pr-30">
    		<div class="row">
    			<div class="col-sm-5">
    				<ul class="footer-link nav navbar-nav">
    					<li class="logo-footer"><a href="#">help</a></li>
    					<li class="logo-footer"><a href="#">terms</a></li>
    					<li class="logo-footer"><a href="#">privacy</a></li>
    				</ul>
    			</div>
    			<div class="col-sm-7 text-right">
    				<p>2016 &copy; Kenny. Pampered by Hencework</p>
    			</div>
    		</div>
    	</footer>
    	<!-- /Footer -->

    </div>
    <!-- /Main Content -->
</div>
<!-- /#wrapper -->

app/views/pages/index.html.erb
<% content_for :head do %>
  <!-- Morris Charts CSS -->
  <link href="vendors/bower_components/morris.js/morris.css" rel="stylesheet" type="text/css"/>
  <!-- Data table CSS -->
  <link href="vendors/bower_components/datatables/media/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css"/>
  <link href="vendors/bower_components/jquery-toast-plugin/dist/jquery.toast.min.css" rel="stylesheet" type="text/css">
<% end %>

<% content_for :bottom do %>
  <!-- Data table JavaScript -->
  <script src="vendors/bower_components/datatables/media/js/jquery.dataTables.min.js"></script>

  <!-- Slimscroll JavaScript -->
  <script src="dist/js/jquery.slimscroll.js"></script>

  <!-- simpleWeather JavaScript -->
  <script src="vendors/bower_components/moment/min/moment.min.js"></script>
  <script src="vendors/bower_components/simpleWeather/jquery.simpleWeather.min.js"></script>
  <script src="dist/js/simpleweather-data.js"></script>

  <!-- Progressbar Animation JavaScript -->
  <script src="vendors/bower_components/waypoints/lib/jquery.waypoints.min.js"></script>
  <script src="vendors/bower_components/Counter-Up/jquery.counterup.min.js"></script>

  <!-- Fancy Dropdown JS -->
  <script src="dist/js/dropdown-bootstrap-extended.js"></script>

  <!-- Sparkline JavaScript -->
  <script src="vendors/jquery.sparkline/dist/jquery.sparkline.min.js"></script>

  <!-- ChartJS JavaScript -->
  <script src="vendors/chart.js/Chart.min.js"></script>

  <!-- Morris Charts JavaScript -->
  <script src="vendors/bower_components/raphael/raphael.min.js"></script>
  <script src="vendors/bower_components/morris.js/morris.min.js"></script>
  <script src="dist/js/morris-data.js"></script>

  <script src="dist/js/dashboard-data.js"></script>
<% end %>

<div class="wrapper">
	<%= render 'layouts/topnav' %>
  <%= render 'layouts/sidebar-left' %>
  <%= render 'layouts/sidebar-right' %>


    <!-- Main Content -->
<div class="page-wrapper">
    <div class="container-fluid">

		<!-- Title -->
		<div class="row heading-bg  bg-red">
			<div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
				<h5 class="txt-light">analytical</h5>
			</div>
			<!-- Breadcrumb -->
			<div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
				<ol class="breadcrumb">
					<li><a href="index.html">Dashboard</a></li>
					<li><a href="#"><span>dashboard</span></a></li>
					<li class="active"><span>analytical</span></li>
				</ol>
			</div>
			<!-- /Breadcrumb -->
		</div>
		<!-- /Title -->

    <!-- Row -->
		<div class="row">
			<div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
				<div class="panel panel-default card-view pa-0">
					<div class="panel-wrapper collapse in">
						<div class="panel-body pa-0">
							<div class="sm-data-box bg-green">
								<div class="row ma-0">
									<div class="col-xs-5 text-center pa-0 icon-wrap-left">
										<i class="icon-diamond txt-light"></i>
									</div>
									<div class="col-xs-7 text-center data-wrap-right">
										<h6 class="txt-light">Registrations</h6>
										<span class="txt-light counter counter-anim"><%= @registrations.count %></span>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div id="weather_3" class="panel panel-default card-view pa-0 weather-info">
					<div class="panel-wrapper collapse in">
						<div class="panel-body pa-0">
							<div class="row ma-0">
								<div class="col-xs-6 pa-0">
									<div class="left-block-wrap pa-30">
										<p class="block nowday"></p>
										<span class="block nowdate"></span>
										<div class="left-block  mt-15"></div>
									</div>
								</div>
								<div class="col-xs-6 pa-0">
									<div class="right-block-wrap pa-30">
										<div class="right-block"></div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="col-lg-9 col-md-8 col-sm-7 col-xs-12">
				<div class="panel panel-default card-view">
					<div class="panel-heading">
						<div class="pull-left">
							<h6 class="panel-title txt-dark">Latest registrations</h6>
						</div>
						<div class="clearfix"></div>
					</div>
					<div class="panel-wrapper collapse in">
						<div class="panel-body">
							<div class="table-wrap">
								<div class="table-responsive">
									<table class="table display product-overview" id="registrations">
										<thead>
											<tr>
												<th>Full Name</th>
												<th>Email</th>
												<th>Phone</th>
												<th>Address</th>
												<th>Score</th>
                        <th>Action</th>
											</tr>
										</thead>
										<tbody>
                      <% @registrations.each do |r| %>
                      <tr>
												<td><%= r.fullName %></td>
												<td><%= r.email %></td>
												<td><%= r.phone %></td>
												<td><%= r.address %></td>
												<td><%= r.potentialScore %></td>
                        <td>
                          <%= link_to 'Details', details_path(r) ,class: "btn btn-sm btn-primary" %>
                          <%= link_to 'Delete', dashboard_path ,class: "btn btn-sm btn-danger" %>
                        </td>
											</tr>
                      <% end %>
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Row -->

		<!-- Row -->
		<div class="row">
			<div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
				<div class="panel panel-default card-view">
					<div class="panel-heading">
						<div class="pull-left">
							<h6 class="panel-title txt-dark">Conversion Rate</h6>
						</div>
						<div class="clearfix"></div>
					</div>
					<div class="panel-wrapper collapse in">
						<div class="panel-body">
							<div class="sm-graph-box">
								<div class="row">
									<div class="col-xs-6">
										<div id="sparkline_1"></div>
									</div>
									<div class="col-xs-6">
										<div class="counter-wrap text-right">
											<span class="counter-cap"><i class="fa  fa-level-up txt-success"></i></span><span class="counter">23</span><span>%</span>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
					<div class="panel panel-default card-view">
						<div class="panel-heading">
							<div class="pull-left">
								<h6 class="panel-title txt-dark">Total Visits</h6>
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="panel-wrapper collapse in">
							<div class="panel-body">
								<div class="sm-graph-box">
									<div class="row">
										<div class="col-xs-6">
											<div id="sparkline_2"></div>
										</div>
										<div class="col-xs-6">
											<div class="counter-wrap text-right">
												<span class="counter-cap"><i class="fa  fa-level-up txt-success"></i></span><span class="counter">12</span><span>m</span>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="panel panel-default card-view">
						<div class="panel-heading">
							<div class="pull-left">
								<h6 class="panel-title txt-dark">downloads</h6>
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="panel-wrapper collapse in">
							<div class="panel-body">
								<div class="sm-graph-box">
									<div class="row">
										<div class="col-xs-6">
											<div id="sparkline_6"></div>
										</div>
										<div class="col-xs-6">
											<div class="counter-wrap text-right">
												<span class="counter-cap"><i class="fa  fa-level-down txt-danger"></i></span><span class="counter">1122</span>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>

			</div>
			<div class="col-lg-9 col-md-8 col-sm-7 col-xs-12">
				<div class="panel panel-default card-view">
					<div class="panel-heading">
						<div class="pull-left">
							<h6 class="panel-title txt-dark"><i class="icon-share mr-10"></i>Visits Conversion</h6>
						</div>
						<div class="clearfix"></div>
					</div>
					<div class="panel-wrapper collapse in">
                            <div class="panel-body">
							<canvas id="chart_1" height="417"></canvas>
						</div>
                        </div>
                    </div>
			</div>
		</div>
		<!-- /Row -->

		<div class="row">
			<div class="col-lg-3 col-md-6">
				<div class="panel panel-primary card-view">
					<div class="panel-heading mb-20">
						<div class="pull-left">
							<h6 class="panel-title txt-light">top countries</h6>
						</div>
						<div class="clearfix"></div>
					</div>
					<div class="panel-wrapper collapse in">
						<div class="panel-body">
							<div class="table-wrap">
								<div class="table-responsive">
									<table  class="table  top-countries" >
										<tbody>
											<tr>
												<td>
													<img src="dist/img/country/gb.svg" alt="user_img">
												</td>
												<td>
													United Kingdom
												</td>
												<td>
													$50
												</td>
											</tr>
											<tr>
												<td>
													<img src="dist/img/country/my.svg" alt="user_img">
												</td>
												<td>
													Malaysia
												</td>
												<td>
													$20
												</td>
											</tr>
											<tr>
												<td>
													<img src="dist/img/country/au.svg" alt="user_img">
												</td>
												<td>
													Australia
												</td>
												<td>
													$5
												</td>
											</tr>

											<tr>
												<td>
													<img src="dist/img/country/us.svg" alt="user_img">
												</td>
												<td>
													United States
												</td>
												<td>
													$5
												</td>
											</tr>
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-3 col-md-6">
				<div class="panel panel-default card-view">
					<div class="panel-heading">
						<div class="pull-left">
							<h6 class="panel-title txt-dark"><i class="icon-pie-chart mr-10"></i>Impressions</h6>
						</div>
						<div class="clearfix"></div>
					</div>
					<div class="panel-wrapper collapse in">
						<div class="panel-body">
							<canvas id="chart_6" height="280"></canvas>
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-6 col-md-12">
                    <div class="panel panel-default card-view">
					<div class="panel-heading">
						<div class="pull-left">
							<h6 class="panel-title txt-dark"><i class="icon-clock mr-10"></i>Average Position</h6>
						</div>
						<div class="clearfix"></div>
					</div>
					<div class="panel-wrapper collapse in">
						<div class="panel-body">
							<div id="morris_extra_line_chart" class="morris-chart" style="height:280px;"></div>
						</div>
					</div>
				</div>
			</div>

		</div>


	</div>
	<!-- Footer -->
	<footer class="footer container-fluid pl-30 pr-30">
		<div class="row">
			<div class="col-sm-5">
				<a href="index.html" class="brand mr-30"><img src="dist/img/logo-sm.png" alt="logo"/></a>
				<ul class="footer-link nav navbar-nav">
					<li class="logo-footer"><a href="#">help</a></li>
					<li class="logo-footer"><a href="#">terms</a></li>
					<li class="logo-footer"><a href="#">privacy</a></li>
				</ul>
			</div>
			<div class="col-sm-7 text-right">
				<p>2016 &copy; Kenny. Pampered by Hencework</p>
			</div>
		</div>
	</footer>
	<!-- /Footer -->

</div>
    <!-- /Main Content -->

</div>
<!-- /#wrapper -->